config/routes.rb
Rails.application.routes.draw do
	root to: 'images#index'
  devise_for :users, path: 'auth', path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }
  resources :images do
  	resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :image
  belongs_to :parent, class_name: 'Comment', optional: true

  has_many :replies, class_name: 'Comment', foreign_key: :parent_id, dependent: :destroy
end

app/models/image.rb
class Image < ApplicationRecord
  has_attached_file :picture, styles: { medium: "300>x300", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :picture, content_type: /\Aimage\/.*\z/
  belongs_to :user

  has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :images, dependent: :destroy
  has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :authenticate_user!

  def create
  	@image = Image.find(params[:image_id])
    @comment = @image.comments.build(comment_params)
    @comment.user_id = current_user.id

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @image, notice: 'Comment was successfully added.' }
        format.json { render :show, status: :created, location: @image }
      else
        format.html { redirect_to @image, notice: 'There was some error.' }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

	def destroy
    @comment = Comment.find(params[:id])
    @image = @comment.image
    @comment.destroy if @comment.user == current_user
    respond_to do |format|
      format.html { redirect_to @image, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
	end

	private
    def comment_params
      params.require(:comment).permit(:message, :parent_id, :image_id)
    end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :set_image, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /images
  # GET /images.json
  def index
    @images = Image.all
  end

  # GET /images/1
  # GET /images/1.json
  def show
    @comments = @image.comments
    @comment = @image.comments.build
  end

  # GET /images/new
  def new
    @image = Image.new
  end

  # GET /images/1/edit
  def edit
  end

  # POST /images
  # POST /images.json
  def create
    @image = current_user.images.new(image_params)

    respond_to do |format|
      if @image.save
        format.html { redirect_to @image, notice: 'Image was successfully created.' }
        format.json { render :show, status: :created, location: @image }
      else
        format.html { render :new }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /images/1
  # PATCH/PUT /images/1.json
  def update
    respond_to do |format|
      if @image.update(image_params)
        format.html { redirect_to @image, notice: 'Image was successfully updated.' }
        format.json { render :show, status: :ok, location: @image }
      else
        format.html { render :edit }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /images/1
  # DELETE /images/1.json
  def destroy
    @image.destroy
    respond_to do |format|
      format.html { redirect_to images_url, notice: 'Image was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_image
      @image = Image.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def image_params
      params.require(:image).permit(:title, :picture, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/comments/_form.html.slim
= simple_form_for [@image, comment] do |f|
	= f.hidden_field :parent_id, input_html: {value: comment.parent_id}
	= f.input :message, label: "Add a #{type}"
	.actions
		= f.button :submit, "#{type}"

app/views/images/_form.html.slim
= simple_form_for @image do |f|
  - if @image.errors.any?
    #error_explanation
      h2
        = pluralize(@image.errors.count, "error")
        | prohibited this image from being saved:
      ul
        - @image.errors.full_messages.each do |message|
          li= message
  = f.input :title
  = f.input :picture, as: :file
  .actions
    = f.button :submit

app/views/images/edit.html.slim
h1
  | Editing Image
= render 'form', image: @image

app/views/images/index.html.slim
h1
  b Gallery
  .pull-right = link_to 'New Image', new_image_path if current_user
.masonry-gallery
	- @images.each do |img|
		= link_to image_path(img) do
		  = image_tag img.picture.url(:medium)
br

app/views/images/new.html.slim
h1
  | New Image
= render 'form', image: @image

app/views/images/show.html.slim
= image_tag @image.picture, class: 'full-width'
.actions.pull-right
	= link_to 'Delete image', @image, data: { confirm: 'Are you sure?' }, method: :delete if @image.user == current_user
.add-comment
	= render 'comments/form', comment: @image.comments.build, type: 'comment' if current_user

.comments
	- @comments.select{|c| c.message.present?}.each do |comment|
		hr
		= comment.user.try(:email)
		.pull-right
			= link_to 'Delete', image_comment_path(@image, comment) , data: { confirm: 'Are you sure?' }, method: :delete if current_user && comment.user == current_user
			- if current_user
				a.reply Reply
		br
		b = comment.message	
		br
		.reply-form
			= render 'comments/form', comment: comment.replies.build, type: 'reply' if current_user
		.col-xs-11.col-xs-offset-1.replies
			- comment.replies.each do |reply|
				br
				= reply.user.try(:email)
				br
				b = reply.message	
				br

= link_to 'Back', images_path

app/views/layouts/_alerts.html.slim
- if flash[:notice]
	.alert.alert-info.alert-dismissable
		a.close aria-label="close" data-dismiss="alert" href="#"  X
		= flash[:notice]
- if flash[:alert]
	.alert.alert-danger.alert-dismissable
		a.close aria-label="close" data-dismiss="alert" href="#"  X
		= flash[:alert]

app/views/layouts/_header.html.slim
nav.navbar.navbar-default.navbar-fixed-top
  .container-fluid
    .navbar-header
      button.navbar-toggle.collapsed[type="button" data-toggle="collapse" data-target="#collapse-1" aria-expanded="false"]
        span.sr-only
          | Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      a.navbar-brand[href="/"]
        | ImageUploader
    #collapse-1.collapse.navbar-collapse
      ul.nav.navbar-nav.navbar-right
        - if current_user
          li
            = link_to 'Log out', destroy_user_session_path, method: :delete
        - else
          li
            = link_to 'Log in', new_user_session_path
          li
            = link_to 'Sign up', new_user_registration_path

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | ImageUploader
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = render 'layouts/header'
    = render 'layouts/alerts'
  body
    #content.col-xs-12.col-sm-10.col-sm-offset-1.col-md-8.col-md-offset-2.col-lg-6.col-lg-offset-3
      = yield